USE SQLDETECTIVE;
LOAD DATA LOCAL INFILE '../../data/security.del'  INTO TABLE security CHARACTER SET latin1 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n';
LOAD DATA LOCAL INFILE '../../data/employee.del'  INTO TABLE employee CHARACTER SET latin1 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n';
LOAD DATA LOCAL INFILE '../../data/lobby.del'  INTO TABLE lobby CHARACTER SET latin1 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n';
LOAD DATA LOCAL INFILE '../../data/hardware.del'  INTO TABLE hardware CHARACTER SET latin1 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n';

