LOAD DATA LOCAL INFILE '../../data/security.del'  INTO TABLE SECURITY CHARACTER SET latin1 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n';
LOAD DATA LOCAL INFILE '../../data/employee.del'  INTO TABLE EMPLOYEE CHARACTER SET latin1 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n';
LOAD DATA LOCAL INFILE '../../data/lobby.del'  INTO TABLE LOBBY CHARACTER SET latin1 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n';
LOAD DATA LOCAL INFILE '../../data/hardware.del'  INTO TABLE HARDWARE CHARACTER SET latin1 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n';

